return {
  { import = "plugins.theme" },
  { import = "plugins.hints" },
  { import = "plugins.navigation" },
  { import = "plugins.lsp" },
  { import = "plugins.brackets" },
  { import = "plugins.markdown" },
  { import = "plugins.git" },
  { import = "plugins.snippets" },
  { import = "plugins.tex" },
  { import = "plugins.typst" },
  { import = "plugins.plugins_dev" },
  { import = "plugins.image" },
  { import = "plugins.quarto" },
  { import = "plugins.cpp" },
  { import = "plugins.math" },
  { import = "plugins.tables" },
  { import = "plugins.fun" },
  { import = "plugins.editor" },
}
